version: "3"
services:
  init-db:
    image: guacamole/guacamole:latest
    command: ["/bin/sh", "-c", "test -e /init/initdb.sql && echo 'init file already exists' || /opt/guacamole/bin/initdb.sh --postgres > /init/initdb.sql" ]
    volumes:
      - dbinit:/init

  db:
    container_name: guacamole_db     
    image: postgres:latest
    restart: unless-stopped
    volumes:  
      - dbinit:/docker-entrypoint-initdb.d    
      - ./dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-guacdb}
      POSTGRES_PASSWORD:
    depends_on:
      - init-db

  daemon:
    container_name: guacamole_daemon     
    image: guacamole/guacd:latest
    restart: unless-stopped

  web:
    container_name: guacamole_web      
    image: guacamole/guacamole:latest
    restart: unless-stopped
    expose:
      - "8080"
    environment:
      GUACD_HOSTNAME: daemon
      POSTGRES_HOSTNAME: db
      POSTGRES_DATABASE: ${POSTGRES_USER:-guacdb}
      POSTGRES_USER: ${POSTGRES_USER:-guacdb}
      POSTGRES_PASSWORD:
    depends_on:
      - db
      - daemon
    networks:
      - default      
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web-guacamole.rule=Host(`guacamole.arrowdemo.se`)"
      - "traefik.http.routers.web-guacamole.tls=true"
      - "traefik.http.routers.web-guacamole.tls.certresolver=le"
      - "traefik.http.routers.web-guacamole.middlewares=add-guacamole"
      - "traefik.http.middlewares.add-guacamole.addprefix.prefix=/guacamole"
networks:
  web:
    external: true

volumes:
  dbinit:
